export interface DictionaryItem {
  name: string;
  category: 'specific' | 'good' | 'normal' | 'forbidden';
  type: string;
  desc?: string;
}

export interface TypeCategory {
  id: string;
  name: string;
  emoji: string;
}

export const DICTIONARY_TYPES: TypeCategory[] = [
  { id: 'all', name: '전체 보기', emoji: '🔍' },
  { id: 'grain', name: '곡류', emoji: '🌾' },
  { id: 'vegetable', name: '채소·과일·견과', emoji: '🍏' },
  { id: 'meat', name: '어·육류·콩·알류', emoji: '🥩' },
  { id: 'juice', name: '야채즙', emoji: '🥤' },
  { id: 'sauce', name: '조미료', emoji: '🧂' },
  { id: 'etc', name: '기호식품·차', emoji: '🍵' },
];

export const DICTIONARY_ITEMS: DictionaryItem[] = [
  // 1. 곡류 (grain)
  { name: '멥쌀현미', category: 'specific', type: 'grain' },
  { name: '메옥수수', category: 'specific', type: 'grain' },
  { name: '율무', category: 'good', type: 'grain' },
  { name: '좁쌀', category: 'good', type: 'grain' },
  { name: '멥쌀(백미)', category: 'normal', type: 'grain' },
  { name: '조', category: 'normal', type: 'grain' },
  { name: '메흑미', category: 'normal', type: 'grain' },
  { name: '강낭콩', category: 'forbidden', type: 'grain' },
  { name: '검은콩', category: 'forbidden', type: 'grain' },
  { name: '노란콩', category: 'forbidden', type: 'grain' },
  { name: '녹두', category: 'forbidden', type: 'grain' },
  { name: '메밀', category: 'forbidden', type: 'grain' },
  { name: '밀가루', category: 'forbidden', type: 'grain' },
  { name: '보리', category: 'forbidden', type: 'grain' },
  { name: '완두콩', category: 'forbidden', type: 'grain' },
  { name: '찹쌀', category: 'forbidden', type: 'grain' },
  { name: '팥', category: 'forbidden', type: 'grain' },
  { name: '오트밀(귀리)', category: 'forbidden', type: 'grain' },
  { name: '찹쌀현미', category: 'forbidden', type: 'grain' },
  { name: '통밀', category: 'forbidden', type: 'grain' },

  // 2. 채소, 해조류, 과일 및 견과류 (vegetable)
  { name: '당근', category: 'specific', type: 'vegetable' },
  { name: '민들레', category: 'specific', type: 'vegetable' },
  { name: '도라지', category: 'specific', type: 'vegetable' },
  { name: '샐러리', category: 'specific', type: 'vegetable' },
  { name: '갓', category: 'specific', type: 'vegetable' },
  { name: '두릅', category: 'specific', type: 'vegetable' },
  { name: '비트', category: 'specific', type: 'vegetable' },
  { name: '표고버섯', category: 'specific', type: 'vegetable' },
  { name: '브로콜리', category: 'specific', type: 'vegetable' },
  { name: '신선초(명일엽)', category: 'specific', type: 'vegetable' },
  { name: '컴프리', category: 'specific', type: 'vegetable' },
  { name: '곤약', category: 'specific', type: 'vegetable' },
  { name: '냉이', category: 'specific', type: 'vegetable' },
  { name: '김', category: 'specific', type: 'vegetable' },
  { name: '돌나물', category: 'specific', type: 'vegetable' },
  { name: '치커리', category: 'specific', type: 'vegetable' },
  { name: '연근', category: 'specific', type: 'vegetable' },
  { name: '곰취', category: 'specific', type: 'vegetable' },
  { name: '마', category: 'specific', type: 'vegetable' },
  { name: '순무', category: 'specific', type: 'vegetable' },
  { name: '참마', category: 'specific', type: 'vegetable' },
  { name: '루꼴라(로켓샐러드)', category: 'specific', type: 'vegetable' },
  { name: '물냉이(크레스)', category: 'specific', type: 'vegetable' },
  { name: '매실', category: 'specific', type: 'vegetable' },
  { name: '밤', category: 'specific', type: 'vegetable' },
  { name: '아보카도', category: 'specific', type: 'vegetable' },
  { name: '파파야', category: 'specific', type: 'vegetable' },
  { name: '살구', category: 'specific', type: 'vegetable' },
  { name: '석류', category: 'specific', type: 'vegetable' },
  { name: '잣', category: 'specific', type: 'vegetable' },
  { name: '파인애플', category: 'specific', type: 'vegetable' },
  { name: '재래종사과', category: 'specific', type: 'vegetable' },
  { name: '아몬드', category: 'specific', type: 'vegetable' },
  { name: '버찌(체리)', category: 'specific', type: 'vegetable' },
  { name: '아사이베리', category: 'specific', type: 'vegetable' },
  { name: '유자', category: 'specific', type: 'vegetable' },
  { name: '월귤(크랜베리)', category: 'specific', type: 'vegetable' },

  { name: '청각', category: 'good', type: 'vegetable' },
  { name: '송이버섯', category: 'good', type: 'vegetable' },
  { name: '아스파라거스', category: 'good', type: 'vegetable' },
  { name: '우뭇가사리', category: 'good', type: 'vegetable' },
  { name: '참나물', category: 'good', type: 'vegetable' },
  { name: '혼잎나물(홑잎나물)', category: 'good', type: 'vegetable' },
  { name: '돼지감자', category: 'good', type: 'vegetable' },
  { name: '소리쟁이', category: 'good', type: 'vegetable' },
  { name: '참취', category: 'good', type: 'vegetable' },
  { name: '카사바(타피오카, 유까, 얌, 만디오까)', category: 'good', type: 'vegetable' },
  { name: '콜리플라워', category: 'good', type: 'vegetable' },
  { name: '한천', category: 'good', type: 'vegetable' },
  { name: '감자', category: 'good', type: 'vegetable' },
  { name: '고수', category: 'good', type: 'vegetable' },
  { name: '고추', category: 'good', type: 'vegetable' },
  { name: '고추잎', category: 'good', type: 'vegetable' },
  { name: '달래', category: 'good', type: 'vegetable' },
  { name: '마늘', category: 'good', type: 'vegetable' },
  { name: '목이버섯', category: 'good', type: 'vegetable' },
  { name: '무잎', category: 'good', type: 'vegetable' },
  { name: '미나리', category: 'good', type: 'vegetable' },
  { name: '부추', category: 'good', type: 'vegetable' },
  { name: '산달래', category: 'good', type: 'vegetable' },
  { name: '쑥', category: 'good', type: 'vegetable' },
  { name: '양파', category: 'good', type: 'vegetable' },
  { name: '올방개(묵)', category: 'good', type: 'vegetable' },
  { name: '죽순', category: 'good', type: 'vegetable' },
  { name: '톳', category: 'good', type: 'vegetable' },
  { name: '파', category: 'good', type: 'vegetable' },
  { name: '파래', category: 'good', type: 'vegetable' },
  { name: '파슬리', category: 'good', type: 'vegetable' },
  { name: '파프리카', category: 'good', type: 'vegetable' },
  { name: '버섯류', category: 'good', type: 'vegetable' },
  { name: '올리브', category: 'good', type: 'vegetable' },
  { name: '개암(헤이즐넛)', category: 'good', type: 'vegetable' },
  { name: '람부탄', category: 'good', type: 'vegetable' },
  { name: '피스타치오', category: 'good', type: 'vegetable' },
  { name: '복숭아', category: 'good', type: 'vegetable' },
  { name: '수박', category: 'good', type: 'vegetable' },
  { name: '은행', category: 'good', type: 'vegetable' },
  { name: '토마토', category: 'good', type: 'vegetable' },
  { name: '호두', category: 'good', type: 'vegetable' },
  { name: '아로니아베리(블랙초크베리)', category: 'good', type: 'vegetable' },

  { name: '교나(경수채)', category: 'normal', type: 'vegetable' },
  { name: '도토리(묵)', category: 'normal', type: 'vegetable' },
  { name: '마늘쫑', category: 'normal', type: 'vegetable' },
  { name: '모자반', category: 'normal', type: 'vegetable' },
  { name: '무릇', category: 'normal', type: 'vegetable' },
  { name: '무순', category: 'normal', type: 'vegetable' },
  { name: '상수리', category: 'normal', type: 'vegetable' },
  { name: '쑥갓', category: 'normal', type: 'vegetable' },
  { name: '엉겅퀴(밀크시슬)', category: 'normal', type: 'vegetable' },
  { name: '열무', category: 'normal', type: 'vegetable' },
  { name: '원추리', category: 'normal', type: 'vegetable' },
  { name: '취나물', category: 'normal', type: 'vegetable' },
  { name: '피망', category: 'normal', type: 'vegetable' },
  { name: '고비', category: 'normal', type: 'vegetable' },
  { name: '두리안', category: 'normal', type: 'vegetable' },
  { name: '레몬', category: 'normal', type: 'vegetable' },
  { name: '무화과', category: 'normal', type: 'vegetable' },
  { name: '코코넛', category: 'normal', type: 'vegetable' },
  { name: '대추야자', category: 'normal', type: 'vegetable' },

  { name: '고구마', category: 'forbidden', type: 'vegetable' },
  { name: '더덕', category: 'forbidden', type: 'vegetable' },
  { name: '상추', category: 'forbidden', type: 'vegetable' },
  { name: '시금치', category: 'forbidden', type: 'vegetable' },
  { name: '양배추', category: 'forbidden', type: 'vegetable' },
  { name: '오이', category: 'forbidden', type: 'vegetable' },
  { name: '우엉', category: 'forbidden', type: 'vegetable' },
  { name: '케일(콜라드)', category: 'forbidden', type: 'vegetable' },
  { name: '콩나물', category: 'forbidden', type: 'vegetable' },
  { name: '호박', category: 'forbidden', type: 'vegetable' },
  { name: '곤드레', category: 'forbidden', type: 'vegetable' },
  { name: '봄동', category: 'forbidden', type: 'vegetable' },
  { name: '가지', category: 'forbidden', type: 'vegetable' },
  { name: '고들빼기', category: 'forbidden', type: 'vegetable' },
  { name: '근대', category: 'forbidden', type: 'vegetable' },
  { name: '다시마', category: 'forbidden', type: 'vegetable' },
  { name: '들깻잎', category: 'forbidden', type: 'vegetable' },
  { name: '로메인', category: 'forbidden', type: 'vegetable' },
  { name: '머위(대)', category: 'forbidden', type: 'vegetable' },
  { name: '미역', category: 'forbidden', type: 'vegetable' },
  { name: '감', category: 'forbidden', type: 'vegetable' },
  { name: '딸기', category: 'forbidden', type: 'vegetable' },
  { name: '땅콩', category: 'forbidden', type: 'vegetable' },
  { name: '라임', category: 'forbidden', type: 'vegetable' },
  { name: '바나나', category: 'forbidden', type: 'vegetable' },
  { name: '배', category: 'forbidden', type: 'vegetable' },
  { name: '부사사과', category: 'forbidden', type: 'vegetable' },
  { name: '자두(푸룬)', category: 'forbidden', type: 'vegetable' },
  { name: '참외', category: 'forbidden', type: 'vegetable' },
  { name: '키위', category: 'forbidden', type: 'vegetable' },
  { name: '포도', category: 'forbidden', type: 'vegetable' },
  { name: '해바라기씨', category: 'forbidden', type: 'vegetable' },
  { name: '천혜향(레드향)', category: 'forbidden', type: 'vegetable' },
  { name: '블루베리', category: 'forbidden', type: 'vegetable' },
  { name: '용과(드래곤후르츠)', category: 'forbidden', type: 'vegetable' },
  { name: '오디', category: 'forbidden', type: 'vegetable' },
  { name: '오렌지', category: 'forbidden', type: 'vegetable' },
  { name: '구아바', category: 'forbidden', type: 'vegetable' },
  { name: '금귤', category: 'forbidden', type: 'vegetable' },
  { name: '망고', category: 'forbidden', type: 'vegetable' },

  // 3. 어·육류 및 콩·알류 (meat)
  { name: '민물뱀장어', category: 'specific', type: 'meat' },
  { name: '민물참게', category: 'specific', type: 'meat' },
  { name: '숭어', category: 'specific', type: 'meat' },
  { name: '잉어', category: 'specific', type: 'meat' },

  { name: '민물새우', category: 'good', type: 'meat' },
  { name: '메기', category: 'good', type: 'meat' },
  { name: '우렁이', category: 'good', type: 'meat' },
  { name: '농어', category: 'good', type: 'meat' },
  { name: '달팽이', category: 'good', type: 'meat' },
  { name: '미꾸라지', category: 'good', type: 'meat' },
  { name: '쇠고기(소고기)', category: 'good', type: 'meat', desc: '치료 90일 이후부터 안전하게 섭취 가능, 그 전에는 주의 요망' },
  { name: '쏘가리', category: 'good', type: 'meat' },
  { name: '연어', category: 'good', type: 'meat' },
  { name: '올갱이', category: 'good', type: 'meat' },
  { name: '재첩조개', category: 'good', type: 'meat' },
  { name: '틸라피아(태래어)', category: 'good', type: 'meat' },

  { name: '가물치', category: 'normal', type: 'meat' },
  { name: '다슬기', category: 'normal', type: 'meat' },
  { name: '민물가재', category: 'normal', type: 'meat' },
  { name: '빙어', category: 'normal', type: 'meat' },
  { name: '빠가사리', category: 'normal', type: 'meat' },
  { name: '송어', category: 'normal', type: 'meat' },
  { name: '은어', category: 'normal', type: 'meat' },

  { name: '돼지고기', category: 'forbidden', type: 'meat' },
  { name: '닭고기', category: 'forbidden', type: 'meat' },
  { name: '달걀', category: 'forbidden', type: 'meat' },
  { name: '낙지', category: 'forbidden', type: 'meat' },
  { name: '붕어', category: 'forbidden', type: 'meat' },
  { name: '조개류 일체', category: 'forbidden', type: 'meat' },
  { name: '바다생선류 일체', category: 'forbidden', type: 'meat', desc: '고등어, 복어, 가자미, 청어, 정어리, 꽁치, 멸치 등 일체 금지 (연어, 숭어, 농어 제외)' },
  { name: '두부', category: 'forbidden', type: 'meat' },
  { name: '멸치', category: 'forbidden', type: 'meat' },
  { name: '굴', category: 'forbidden', type: 'meat' },
  { name: '꼬막', category: 'forbidden', type: 'meat' },
  { name: '꽃게', category: 'forbidden', type: 'meat' },
  { name: '고래고기', category: 'forbidden', type: 'meat' },

  // 4. 야채즙 (juice)
  { name: '당근즙', category: 'specific', type: 'juice' },
  { name: '민들레즙', category: 'specific', type: 'juice' },
  { name: '샐러리즙', category: 'specific', type: 'juice' },
  { name: '비트즙', category: 'specific', type: 'juice' },
  { name: '브로콜리즙', category: 'specific', type: 'juice' },
  { name: '신선초(명일엽)즙', category: 'specific', type: 'juice' },
  { name: '컴프리즙', category: 'specific', type: 'juice' },
  { name: '치커리즙', category: 'specific', type: 'juice' },
  { name: '마즙', category: 'specific', type: 'juice' },

  { name: '감자즙', category: 'good', type: 'juice' },
  { name: '미나리즙', category: 'good', type: 'juice' },
  { name: '쑥즙', category: 'good', type: 'juice' },
  { name: '파슬리즙', category: 'good', type: 'juice' },

  { name: '순무즙', category: 'normal', type: 'juice' },
  { name: '쑥갓즙', category: 'normal', type: 'juice' },

  { name: '고구마즙', category: 'forbidden', type: 'juice' },
  { name: '시금치즙', category: 'forbidden', type: 'juice' },
  { name: '양배추즙', category: 'forbidden', type: 'juice' },
  { name: '오이즙', category: 'forbidden', type: 'juice' },
  { name: '케일(콜라드)즙', category: 'forbidden', type: 'juice' },
  { name: '로메인즙', category: 'forbidden', type: 'juice' },
  { name: '보리싹즙', category: 'forbidden', type: 'juice' },
  { name: '오크립(오크리프)즙', category: 'forbidden', type: 'juice' },
  { name: '와거즙', category: 'forbidden', type: 'juice' },
  { name: '적채즙', category: 'forbidden', type: 'juice' },
  { name: '청경채즙', category: 'forbidden', type: 'juice' },
  { name: '아세로라즙', category: 'forbidden', type: 'juice' },

  // 5. 조미료 (sauce)
  { name: '(흑)설탕', category: 'specific', type: 'sauce' },
  { name: '참깨', category: 'specific', type: 'sauce' },
  { name: '검은깨', category: 'specific', type: 'sauce' },
  { name: '계피', category: 'specific', type: 'sauce' },

  { name: '올리브유', category: 'good', type: 'sauce' },
  { name: '양조식초(옥수수발효)', category: 'good', type: 'sauce' },
  { name: '참기름', category: 'good', type: 'sauce' },
  { name: '천일염', category: 'good', type: 'sauce' },
  { name: '현미식초', category: 'good', type: 'sauce' },
  { name: '마늘', category: 'good', type: 'sauce' },
  { name: '겨자', category: 'good', type: 'sauce' },
  { name: '고추냉이', category: 'good', type: 'sauce' },
  { name: '버터', category: 'good', type: 'sauce' },
  { name: '생강', category: 'good', type: 'sauce' },
  { name: '월계수', category: 'good', type: 'sauce' },
  { name: '죽염', category: 'good', type: 'sauce' },
  { name: '칠리소스', category: 'good', type: 'sauce' },
  { name: '후추', category: 'good', type: 'sauce' },
  { name: '사프란', category: 'good', type: 'sauce' },

  { name: '옥수수기름', category: 'normal', type: 'sauce' },
  { name: '쌀카레 (밀가루 무첨가)', category: 'normal', type: 'sauce', desc: '밀가루 없는 100% 쌀카레 가루만 허용!' },
  { name: '커민', category: 'normal', type: 'sauce' },
  { name: '토마토케찹', category: 'normal', type: 'sauce' },
  { name: '토하젓', category: 'normal', type: 'sauce' },

  { name: '간장', category: 'forbidden', type: 'sauce' },
  { name: '된장', category: 'forbidden', type: 'sauce' },
  { name: '청국장', category: 'forbidden', type: 'sauce' },
  { name: '들기름', category: 'forbidden', type: 'sauce' },
  { name: '들깨', category: 'forbidden', type: 'sauce' },
  { name: '젓갈류', category: 'forbidden', type: 'sauce' },
  { name: '카놀라유(채종유)', category: 'forbidden', type: 'sauce' },
  { name: '콩기름', category: 'forbidden', type: 'sauce' },
  { name: '포도씨유', category: 'forbidden', type: 'sauce' },
  { name: '해바라기씨유', category: 'forbidden', type: 'sauce' },
  { name: '바질', category: 'forbidden', type: 'sauce' },
  { name: '감식초', category: 'forbidden', type: 'sauce' },
  { name: '까나리액젓', category: 'forbidden', type: 'sauce' },
  { name: '면실유', category: 'forbidden', type: 'sauce' },
  { name: '새우젓', category: 'forbidden', type: 'sauce' },
  { name: '오레가노', category: 'forbidden', type: 'sauce' },
  { name: '춘장', category: 'forbidden', type: 'sauce' },
  { name: '창란젓', category: 'forbidden', type: 'sauce' },
  { name: '방아풀', category: 'forbidden', type: 'sauce' },
  { name: '발사믹식초', category: 'forbidden', type: 'sauce' },

  // 6. 기호식품 (etc)
  { name: '매실차', category: 'specific', type: 'etc' },
  { name: '게르마늄', category: 'specific', type: 'etc' },
  { name: '오미자', category: 'specific', type: 'etc' },
  { name: '클로렐라', category: 'specific', type: 'etc' },
  { name: '석류식초', category: 'specific', type: 'etc' },
  { name: '솔잎', category: 'specific', type: 'etc' },
  { name: '두충', category: 'specific', type: 'etc' },
  { name: '카모마일', category: 'specific', type: 'etc' },
  { name: '스피루리나', category: 'specific', type: 'etc' },
  { name: '영지', category: 'specific', type: 'etc' },
  { name: '요구르트', category: 'specific', type: 'etc' },
  { name: '녹용', category: 'specific', type: 'etc' },
  { name: '율무차', category: 'specific', type: 'etc' },
  { name: '삼백초', category: 'specific', type: 'etc' },
  { name: '오가피', category: 'specific', type: 'etc' },
  { name: '유자차', category: 'specific', type: 'etc' },
  { name: '코코아', category: 'specific', type: 'etc' },

  { name: '누에가루', category: 'good', type: 'etc' },
  { name: '가시오갈피', category: 'good', type: 'etc' },
  { name: '로즈마리', category: 'good', type: 'etc' },
  { name: '카사바', category: 'good', type: 'etc' },
  { name: '비파', category: 'good', type: 'etc' },
  { name: '산둥굴레', category: 'good', type: 'etc' },
  { name: '만수국화(차)', category: 'good', type: 'etc' },
  { name: '꽃가루', category: 'good', type: 'etc' },
  { name: '로얄제리', category: 'good', type: 'etc' },
  { name: '루이보스티', category: 'good', type: 'etc' },
  { name: '마누카(티트리)', category: 'good', type: 'etc' },
  { name: '복숭아씨', category: 'good', type: 'etc' },
  { name: '자라', category: 'good', type: 'etc' },
  { name: '강황', category: 'good', type: 'etc' },
  { name: '동충하초', category: 'good', type: 'etc' },
  { name: '울금(심황)', category: 'good', type: 'etc' },
  { name: '차가버섯', category: 'good', type: 'etc' },

  { name: '쑥차', category: 'normal', type: 'etc' },
  { name: '무엿', category: 'normal', type: 'etc' },
  { name: '아마씨', category: 'normal', type: 'etc' },
  { name: '다크초콜릿', category: 'normal', type: 'etc' },

  { name: '커피 (디카페인 포함 절대 금지)', category: 'forbidden', type: 'etc', desc: '카페인 유무와 상관없이 전면적 금지식품!' },
  { name: '녹차', category: 'forbidden', type: 'etc' },
  { name: '홍차', category: 'forbidden', type: 'etc' },
  { name: '대추', category: 'forbidden', type: 'etc' },
  { name: '결명자', category: 'forbidden', type: 'etc' },
  { name: '스쿠알렌', category: 'forbidden', type: 'etc' },
  { name: '아카시아꿀', category: 'forbidden', type: 'etc' },
  { name: '알로에', category: 'forbidden', type: 'etc' },
  { name: '인삼', category: 'forbidden', type: 'etc' },
  { name: '아가베', category: 'forbidden', type: 'etc' },
  { name: '난황', category: 'forbidden', type: 'etc' },
  { name: '보리지(오일)', category: 'forbidden', type: 'etc' },
  { name: '메밀차', category: 'forbidden', type: 'etc' },
  { name: '초란', category: 'forbidden', type: 'etc' },
  { name: '곶감', category: 'forbidden', type: 'etc' },
  { name: '복분자주', category: 'forbidden', type: 'etc' },
  { name: '감잎차', category: 'forbidden', type: 'etc' },
  { name: '구기자', category: 'forbidden', type: 'etc' }
];
